//? project action types
export const FETCH_PROJECT_ALL = "FETCH_PROJECT_ALL";
export const FETCH_PROJECT_BY_ID = "FETCH_PROJECT_BY_ID";
export const FETCH_PROJECT_BY_SEARCH = "FETCH_PROJECT_BY_SEARCH";
export const CREATE_PROJECT = "CREATE_PROJECT";
export const UPDATE_PROJECT = "UPDATE_PROJECT";
export const DELETE_PROJECT = "DELETE_PROJECT";
export const LIKE_PROJECT = "LIKE_PROJECT";
export const COMMENT_PROJECT = "COMMENT_PROJECT";
